import { Html } from '@react-three/drei';
import { Canvas } from '@react-three/fiber';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Suspense } from 'react';
import Three from '../components/three';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Canvas id='three-canvas-container'>
				<Suspense fallback={null}>
					<Three />
				</Suspense>
			</Canvas>
		</div>
	);
};

export default Home;
